import Head from 'next/head'

import LandingContent from '@/components/page/Landing'

export default function Home() {
  return (
    <>
      <Head>
        <title>Heesoo Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <LandingContent />
    </>
  )
}
